# Generated by Django 4.2.5 on 2023-11-17 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furniture_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='user_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_defects', to=settings.AUTH_USER_MODEL),
        ),
    ]
